// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfCfQeUbi5ciemy_su-RRb-bMzpgz1rlc',
    appId: '1:653683248147:web:c00df11b97a360762743e6',
    messagingSenderId: '653683248147',
    projectId: 'contactllist',
    authDomain: 'contactllist.firebaseapp.com',
    storageBucket: 'contactllist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiJ2ypHv27tLId2i15vab9YaRF4Xma9K8',
    appId: '1:653683248147:android:c457848fbda6690a2743e6',
    messagingSenderId: '653683248147',
    projectId: 'contactllist',
    storageBucket: 'contactllist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO4D-y6ob_sqwJf10VFw8IDj4Ejgk6QHQ',
    appId: '1:653683248147:ios:3b976eea56dfa6442743e6',
    messagingSenderId: '653683248147',
    projectId: 'contactllist',
    storageBucket: 'contactllist.appspot.com',
    iosClientId: '653683248147-4odd9hb52pn62m0l7646phm7au28ffn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO4D-y6ob_sqwJf10VFw8IDj4Ejgk6QHQ',
    appId: '1:653683248147:ios:3b976eea56dfa6442743e6',
    messagingSenderId: '653683248147',
    projectId: 'contactllist',
    storageBucket: 'contactllist.appspot.com',
    iosClientId: '653683248147-4odd9hb52pn62m0l7646phm7au28ffn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
